version: '3.8'
services:
  whois-newest-worker:
    build: .
    image: whois-newest-worker:latest
    env_file:
      - .env
    network_mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
