# ───────────────────────────────────────────────────────────────────────────────
# Cassandra Configuration for ViperScan Cluster 1 on single LVM root volume
# ───────────────────────────────────────────────────────────────────────────────

cluster_name: 'ViperScan Cluster 1'

# Token & replication settings
num_tokens: 16
allocate_tokens_for_local_replication_factor: 3

# Hinted handoff
hinted_handoff_enabled: true
max_hint_window: 3h
hinted_handoff_throttle: 1024KiB
max_hints_delivery_threads: 2
hints_flush_period: 10000ms
max_hints_file_size: 128MiB
auto_hints_cleanup_enabled: false

# Batchlog
batchlog_replay_throttle: 1024KiB
batchlog_endpoint_strategy: dynamic_remote

# Auth (open) & authorization
authenticator:
  class_name: AllowAllAuthenticator
authorizer:
  class_name: AllowAllAuthorizer

# Role & network authorizers (open)
role_manager:
  class_name: CassandraRoleManager
  parameters:
    invalid_role_disconnect_task_period: 4h
    invalid_role_disconnect_task_max_jitter: 1h

network_authorizer:
  class_name: AllowAllNetworkAuthorizer

cidr_authorizer:
  class_name: AllowAllCIDRAuthorizer

# Partitioner
partitioner: org.apache.cassandra.dht.Murmur3Partitioner

# Seed provider (single-node)
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      - seeds: "127.0.0.1:7000"

# ─── STORAGE DIRECTORIES (on your LVM root `/`, ~98 GB) ───────────────────────
data_file_directories:
  - /var/lib/cassandra/data
commitlog_directory: /var/lib/cassandra/commitlog
saved_caches_directory: /var/lib/cassandra/saved_caches
hints_directory: /var/lib/cassandra/hints

# ─── CONCURRENCY TUNING ────────────────────────────────────────────────────────
# NVMe + quad-core box → tune to hardware
concurrent_reads: 32          # 16 × # NVMe drives (1)
concurrent_writes: 32         # 8 × # cores (4)
concurrent_counter_writes: 32
concurrent_compactors: 8      # cores / 2 to limit compaction spikes

# ─── CACHES ───────────────────────────────────────────────────────────────────
key_cache_size: 128MiB       # ~1% heap
row_cache_size: 0MiB         # disabled
file_cache_size: 512MiB      # chunk cache + OS page cache

# ─── MEMTABLES (off-heap) ─────────────────────────────────────────────────────
memtable_allocation_type: offheap_objects
memtable_offheap_space: 2048MiB

# ─── COMMITLOG ────────────────────────────────────────────────────────────────
commitlog_sync: periodic
commitlog_sync_period: 100ms
commitlog_segment_size: 32MiB

# ─── SNAPSHOTS & BACKUPS ──────────────────────────────────────────────────────
snapshot_before_compaction: false
auto_snapshot: true

# ─── COMPACTION ───────────────────────────────────────────────────────────────
default_compaction:
  class_name: UnifiedCompactionStrategy
  parameters:
    scaling_parameters: T4
    max_sstables_to_compact: 16
    target_sstable_size: 64MiB

# ─── NATIVE TRANSPORT (CQL) ───────────────────────────────────────────────────
start_native_transport: true
native_transport_port: 9042
native_transport_allow_older_protocols: true

# ─── RPC / Thrift (if used) ──────────────────────────────────────────────────
rpc_address: localhost
rpc_keepalive: true

# ─── GUARDRAILS: DISK USAGE ───────────────────────────────────────────────────
data_disk_usage_percentage_warn_threshold: 90   # warn at 90% of / volume
data_disk_usage_percentage_fail_threshold: 95   # reject writes at 95%

# ───────────────────────────────────────────────────────────────────────────────
# All other settings remain at their defaults.
# After saving, restart Cassandra:
#   sudo systemctl restart cassandra
# ───────────────────────────────────────────────────────────────────────────────



roles_validity: 2000ms
permissions_validity: 2000ms
credentials_validity: 2000ms
cdc_enabled: false
disk_failure_policy: stop
commit_failure_policy: stop
prepared_statements_cache_size:
row_cache_save_period: 0s
counter_cache_size:
counter_cache_save_period: 7200s
commitlog_disk_access_mode: auto
concurrent_materialized_view_writes: 32
memtable:
  configurations:
    skiplist:
      class_name: SkipListMemtable
    trie:
      class_name: TrieMemtable
    default:
      inherits: trie
trickle_fsync: true
# Min unit: KiB
trickle_fsync_interval: 10240KiB
storage_port: 7000
ssl_storage_port: 7001
listen_address: localhost



incremental_backups: false
snapshot_links_per_second: 0
sstable:
  selected_format: bti
column_index_size: 4KiB

concurrent_materialized_view_builders: 1
compaction_throughput: 64MiB/s
sstable_preemptive_open_interval: 50MiB
uuid_sstable_identifiers_enabled: true
stream_entire_sstables: true
read_request_timeout: 500000ms
range_request_timeout: 1000000ms
write_request_timeout: 1000000ms
counter_write_request_timeout: 100000ms
cas_contention_timeout: 500000ms
truncate_request_timeout: 6000000ms
request_timeout: 1000000ms
slow_query_log_timeout: 50000ms
initial_location_provider: SimpleLocationProvider
node_proximity: NetworkTopologyProximity
dynamic_snitch_update_interval: 100ms
dynamic_snitch_reset_interval: 600000ms
dynamic_snitch_badness_threshold: 1.0
crypto_provider:
  - class_name: org.apache.cassandra.security.DefaultCryptoProvider
    parameters:
      - fail_on_missing_provider: "false"
server_encryption_options:
  internode_encryption: none
  legacy_ssl_storage_port_enabled: false
  # Set to a valid keystore if internode_encryption is dc, rack or all
  keystore: conf/.keystore
  require_client_auth: false
  # Set to a valid trustore if require_client_auth is true
  truststore: conf/.truststore
  require_endpoint_verification: false
client_encryption_options:
  # Enable client-to-server encryption
  enabled: false
  keystore: conf/.keystore
  require_client_auth: false

internode_compression: dc
inter_dc_tcp_nodelay: false
trace_type_query_ttl: 1d
# Min unit: s
trace_type_repair_ttl: 7d
user_defined_functions_enabled: false
triggers_policy: enabled
transparent_data_encryption_options:
  enabled: false
  chunk_length_kb: 64
  cipher: AES/CBC/PKCS5Padding
  key_alias: testing:1
  # CBC IV length for AES needs to be 16 bytes (which is also the default size)
  # iv_length: 16
  key_provider:
    - class_name: org.apache.cassandra.security.JKSKeyProvider
      parameters:
        - keystore: conf/.keystore
          keystore_password: cassandra
          store_type: JCEKS
          key_password: cassandra

tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
replica_filtering_protection:
    cached_rows_warn_threshold: 2000
    cached_rows_fail_threshold: 32000
batch_size_warn_threshold: 50KiB
batch_size_fail_threshold: 5000KiB
# Log WARN on any batches not of type LOGGED than span across more partitions than this limit
unlogged_batch_across_partitions_warn_threshold: 10
audit_logging_options:
  enabled: false
  logger:
    - class_name: BinAuditLogger
diagnostic_events_enabled: false
repaired_data_tracking_for_range_reads_enabled: false
repaired_data_tracking_for_partition_reads_enabled: false
report_unconfirmed_repaired_data_mismatches: false
materialized_views_enabled: false
sasi_indexes_enabled: false
transient_replication_enabled: false
drop_compact_storage_enabled: false
default_secondary_index: sai
default_secondary_index_enabled: true
storage_compatibility_mode: NONE

