############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Projects"
url = "projects/"
weight = 2

[[main]]
weight = 4
name = "Blog"
url = "blog/"


[[main]]
name = "Contact"
url = "contact/"

[[footer]]

name = "Authors"
url = "authors/"

[[footer]]

name = "Categories"
url = "categories/"



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 3


[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
