version: '3.8'
services:
  domainstatus-worker:
    build: .
    image: domain-status-worker:latest
    env_file:
      - .env
    network_mode: host
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
